import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import UserProfileButton from "@/components/UserProfileButton";
import Tab from "@/components/Tab";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Wise Care",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased`}
      >
        <div className="flex w-full justify-between p-4 shadow">
            <h1 className="text-2xl font-bold">WiseCare</h1>
            <UserProfileButton />
        </div>
        {children}
        <Tab/>
      </body>
    </html>
    </ClerkProvider>
  );
}
